# Generated by Django 4.2.7 on 2024-02-01 10:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShortenedUrlStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('clicked', models.BigIntegerField()),
                ('shortened_url', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shortener.shortenedurl')),
            ],
            options={
                'db_table': 'shortened_url_statistics',
                'ordering': ['-date', 'shortened_url'],
                'indexes': [models.Index(fields=['date'], name='shortened_u_date_9021a3_idx'), models.Index(fields=['shortened_url'], name='shortened_u_shorten_45fbdb_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='shortenedurlstatistics',
            constraint=models.UniqueConstraint(fields=('date', 'shortened_url'), name='unique_shortened_url_statistics'),
        ),
    ]
