# Generated by Django 4.2.7 on 2024-02-01 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0002_shortenedurlstatistics_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shortenedurlstatistics',
            name='clicked',
            field=models.BigIntegerField(default=0),
        ),
    ]
